### ISSUE TITLE
关于入口节点地理位置的问题

### ISSUE THREAD

**Issue by aofei** [hydra-yl/globals.sh#1]
你好，不久前偶然发现了这个产品感觉很棒。

我的应用场景是日常连接我在香港的服务器，因为我的主要开发环境是在云端（纯 CLI 开发环境），所以对我来说低时延才是关键，带宽反倒不用那么大。我发现 GlobalSSH 在国内的所有入口节点 IP 的地理位置全在北京，这也就意味着无论我人在哪里我的 IP 包都得先到北京一趟然后才能再绕去广州最后出海到香港，在原本固定的 40ms+ 的”北京-香港“的延迟上还要多出个”我-北京“的延迟。我目前是有一台北京的云服务器来做 jump server，先 Mosh 到北京的服务器然后再通过这款产品 SSH 到香港的服务器，这样做会很稳，总体来说延迟也很低，但只要我人一不在北京还是能感觉到明显的操作卡顿。

所以想问一下，这款产品是否有启用其他省份入口节点的计划？比如入口节点能选在广东省这种。

鉴于网站是纯中文并且产品定位也是国内，所以我就不用英文了，期待回复！😄

**Comment by hydra-yl** [comment]
2周内会增加北上广的就近入口

**Comment by aofei** [comment]
@hydra-yl 

感谢回复！

如果能在 DNS 层面解决，根据来源 IP 就近选择入口节点地理位置的话会是最理想的。但如果是网页端创建实例时手动选择入口节点地理位置的话，那还是非常希望能做成创建后**可编辑的**。因为考虑到该产品单个 IP 只能创建一个实例的情况，对于频繁走动的人来说反复删除并重建实例以修改入口节点地理位置会是一件比较头疼的事情。

❤️

**Comment by hydra-yl** [comment]
1. 是的，利用DNS就近解析
2. 可编辑。如果DNS就近不对或者VPN等，最终用户自己指定

**Comment by hydra-yl** [comment]
> @hydra-yl
> 
> 感谢回复！
> 
> 如果能在 DNS 层面解决，根据来源 IP 就近选择入口节点地理位置的话会是最理想的。但如果是网页端创建实例时手动选择入口节点地理位置的话，那还是非常希望能做成创建后**可编辑的**。因为考虑到该产品单个 IP 只能创建一个实例的情况，对于频繁走动的人来说反复删除并重建实例以修改入口节点地理位置会是一件比较头疼的事情。
> 
> ❤️

Hi，来源 IP就近选择入口节点已经可以用了。具体如下：

- 基础版可以指定入口地域
- 企业版及以上默认就近接入。即一个实例对应3个入口IP，DNS智能解析返回就近的那个。
- 免费版暂时和原来一样

**Comment by aofei** [comment]
刚看了下，北上广三入口可以说是非常合理的选项了。

鉴于问题已解决，issue 就可以关闭了。辛苦了！感谢更新到这里。😄
