### ISSUE TITLE
更多可编辑项以及台北出口节点？

### ISSUE THREAD

**Issue by aofei** [hydra-yl/globals.sh#2]
你好，又来打扰了。

鉴于 GlobalSSH 这款产品已经不再允许个人用户创建，因此还是很希望能够允许用户编辑“源站 IP”以及“源站靠近区域“这两个配置项的，当然我也承认这是站在“老用户”的角度考虑的。我记得在之前修改“源站 IP”或“源站靠近区域”的唯一途径就是删除并重建资源，现在看来对于个人用户来说这显然已经行不通了。其实从很早开始这款产品的“源站端口”就是个可编辑项，因此更多的可编辑项似乎也算是一个合理的需求。

此外，平台新增了台北机房，因此想问一下是否有计划增加台北出口节点优化一下到台北机房的网络线路呢？或许可以仅为收费版增加。

以上，期待回复～❤️

**Comment by aofei** [comment]
ping @hydra-yl 

请问目前有什么想法吗？

**Comment by hydra-yl** [comment]
你好👋，近期因为忙于PathX(GlobalSSH)的大升级版，漏看了issue。我们会讨论一下。

**Comment by hydra-yl** [comment]
以上海到台北为例，分以下3种情况：

1. 上海到台北（高速通道）：47ms
2. 上海到香港（高速通道）+ 香港到台北（高速通道）：33+14=47ms
3. 上海到香港（高速通道）+ 香港到台北（公网）：33+19=52ms

结论：

1. 如果使用GlobalSSH的香港覆盖台北源站，延迟为情况3。
2. 当前的最低延迟为47ms

计划：

1&2比3缩短5ms，意义不大。我们看下是否能做到更低的延迟，与成本有关系。暂时时间无法给出，不好意思。

上海到台北（高速通道）

```
PING 10.41.140.10 (10.41.140.10) 56(84) bytes of data.
64 bytes from 10.41.140.10: icmp_seq=1 ttl=62 time=47.4 ms
64 bytes from 10.41.140.10: icmp_seq=2 ttl=62 time=46.8 ms
64 bytes from 10.41.140.10: icmp_seq=3 ttl=62 time=46.10 ms
64 bytes from 10.41.140.10: icmp_seq=4 ttl=62 time=47.0 ms
64 bytes from 10.41.140.10: icmp_seq=5 ttl=62 time=46.8 ms
64 bytes from 10.41.140.10: icmp_seq=6 ttl=62 time=46.8 ms
64 bytes from 10.41.140.10: icmp_seq=7 ttl=62 time=46.8 ms
64 bytes from 10.41.140.10: icmp_seq=8 ttl=62 time=46.8 ms
64 bytes from 10.41.140.10: icmp_seq=9 ttl=62 time=46.8 ms
64 bytes from 10.41.140.10: icmp_seq=10 ttl=62 time=46.8 ms
```



上海到香港（高速通道）

```
PING 10.7.185.74 (10.7.185.74) 56(84) bytes of data.
64 bytes from 10.7.185.74: icmp_seq=1 ttl=62 time=33.9 ms
64 bytes from 10.7.185.74: icmp_seq=2 ttl=62 time=32.8 ms
64 bytes from 10.7.185.74: icmp_seq=3 ttl=62 time=32.9 ms
64 bytes from 10.7.185.74: icmp_seq=4 ttl=62 time=32.8 ms
64 bytes from 10.7.185.74: icmp_seq=5 ttl=62 time=32.9 ms
64 bytes from 10.7.185.74: icmp_seq=6 ttl=62 time=32.9 ms
64 bytes from 10.7.185.74: icmp_seq=7 ttl=62 time=32.8 ms
64 bytes from 10.7.185.74: icmp_seq=8 ttl=62 time=32.8 ms
64 bytes from 10.7.185.74: icmp_seq=9 ttl=62 time=32.9 ms
64 bytes from 10.7.185.74: icmp_seq=10 ttl=62 time=32.9 ms
```

香港到台北（高速通道）

```
PING 10.41.140.10 (10.41.140.10) 56(84) bytes of data.
64 bytes from 10.41.140.10: icmp_seq=1 ttl=62 time=14.4 ms
64 bytes from 10.41.140.10: icmp_seq=2 ttl=62 time=14.2 ms
64 bytes from 10.41.140.10: icmp_seq=3 ttl=62 time=14.2 ms
64 bytes from 10.41.140.10: icmp_seq=4 ttl=62 time=14.2 ms
64 bytes from 10.41.140.10: icmp_seq=5 ttl=62 time=14.2 ms
64 bytes from 10.41.140.10: icmp_seq=6 ttl=62 time=14.2 ms
64 bytes from 10.41.140.10: icmp_seq=7 ttl=62 time=14.3 ms
64 bytes from 10.41.140.10: icmp_seq=8 ttl=62 time=14.3 ms
64 bytes from 10.41.140.10: icmp_seq=9 ttl=62 time=14.2 ms
64 bytes from 10.41.140.10: icmp_seq=10 ttl=62 time=14.2 ms
```

香港到台北（公网）

```
PING 123.58.197.14 (123.58.197.14) 56(84) bytes of data.
64 bytes from 123.58.197.14: icmp_seq=1 ttl=49 time=20.4 ms
64 bytes from 123.58.197.14: icmp_seq=2 ttl=49 time=19.0 ms
64 bytes from 123.58.197.14: icmp_seq=3 ttl=49 time=18.8 ms
64 bytes from 123.58.197.14: icmp_seq=4 ttl=49 time=18.8 ms
64 bytes from 123.58.197.14: icmp_seq=5 ttl=49 time=18.9 ms
64 bytes from 123.58.197.14: icmp_seq=6 ttl=49 time=18.8 ms
64 bytes from 123.58.197.14: icmp_seq=7 ttl=49 time=18.8 ms
64 bytes from 123.58.197.14: icmp_seq=8 ttl=49 time=18.8 ms
64 bytes from 123.58.197.14: icmp_seq=9 ttl=49 time=18.7 ms
64 bytes from 123.58.197.14: icmp_seq=10 ttl=49 time=18.8 ms
```

**Comment by aofei** [comment]
了解，考虑到成本，以目前贴出的实际数据来看，5ms 的线路优化的确略显奢侈了。

那顺便再问一下是否有考虑增加更多的可编辑项呢？也就是“源站 IP”以及“源站靠近区域“这两个配置项。

**Comment by hydra-yl** [comment]
> 了解，考虑到成本，以目前贴出的实际数据来看，5ms 的线路优化的确略显奢侈了。
> 
> 那顺便再问一下是否有考虑增加更多的可编辑项呢？也就是“源站 IP”以及“源站靠近区域“这两个配置项。

会的。时间可能略晚。确认之后，会在这里回复。

**Comment by hydra-yl** [comment]
![image](https://user-images.githubusercontent.com/32407515/118368115-023a4700-b5d4-11eb-854a-ee31e0dff89e.png)
@aofei FYI 上海到台北最短的路径应该是海峡光缆1号（Taiwan Strait Express 1，TSE-1）。目前GlobalSSH没走这条，理论存在可能。

**Comment by aofei** [comment]
> 目前GlobalSSH没走这条，理论存在可能。

最初在平台官网信息中的 29 条专线图中没有看到这条线路，我以为平台并没有计划投资使用这条。如果能启用这条线路的话，那对台延迟的确就能到最低值了，很诱人。

**Comment by hydra-yl** [comment]
@aofei 已增加台北节点，平均延迟32ms（参见：[gsshstatus](https://gsshstatus.ucloud.cn)）。基于海峡光缆[Taiwan Strait Express 1（TSE1）](https://en.wikipedia.org/wiki/TSE-1)。

**Comment by aofei** [comment]
@hydra-yl 

You've made my day! 🎉

幸苦啦！顺便好奇问上一句，刚在 [GSSHStatus](https://gsshstatus.ucloud.cn) 上有看到线路延迟波动幅度还挺大，低的时候甚至低到过 20ms+，好奇这是什么原因导致的呢？这 10ms 左右的延迟波动是走与不走专线的区别么？

**Comment by hydra-yl** [comment]
> @hydra-yl
> 
> You've made my day! 🎉
> 
> 幸苦啦！顺便好奇问上一句，刚在 [GSSHStatus](https://gsshstatus.ucloud.cn) 上有看到线路延迟波动幅度还挺大，低的时候甚至低到过 20ms+，好奇这是什么原因导致的呢？这 10ms 左右的延迟波动是走与不走专线的区别么？

只要TSE1不中断，都是经过TSE1。剩下的波动与gssh的转发实现有关系，还在看这个问题。实际物理链路的波动在3ms左右。如果TSE1中断，会绕行HK-TW线路
