### ISSUE TITLE
增加首尔出口？

### ISSUE THREAD

**Issue by C018** [hydra-yl/globals.sh#4]
看到PathX是有首尔节点的可否增加首尔出口，使用东京到首尔大概30ms(来自甲骨文首尔机房)。可否增加下首尔出口？

**Comment by allensue325** [comment]
已评估可以增加首尔出口，预计于7月9日上线。

**Comment by C018** [comment]
非常感谢

**Comment by C018** [comment]
可以在https://gsshstatus.ucloud.cn/增加各个节点的延迟吗？比如还有广州或者北京，付费一般是三个出口

**Comment by hydra-yl** [comment]
> 可以在[gsshstatus](https://gsshstatus.ucloud.cn/)增加各个节点的延迟吗？比如还有广州或者北京，付费一般是三个出口

计划2个月后会推出一个UCloud的移动app（可在app store、各大安卓应用商店下载）展示此部分数据。数据分为实时、历史。目前Gsshstatus基于statuspage.io开发，展示的数量和可定制性一般，所以不打算基于此再投入研发精力。

PS：目前在app store、各大安卓应用商店已经可以下载该app，但尚未支持GlobalSSH产品

**Comment by C018** [comment]
试了一下首尔出口延迟还是很高，出口ip107.150.x.x延迟40-50ms，107.155.x.x高达90ms，使用甲骨文首尔(152.70.237.101)测试的，

**Comment by allensue325** [comment]
测试从我们首尔出口到甲骨文首尔(152.70.237.101)延迟的确很高，能否提供下从甲骨文首尔(152.70.237.101)到我们首尔出口的mtr截图。

**Comment by C018** [comment]
添加实例报错 已经存在相同源站IP的加速域名，若您项目下找不到请联系我们处理，请提供需要mtr的ip

**Comment by allensue325** [comment]
首尔出口到甲骨文首尔(152.70.237.101)延迟高的问题已解决，主要为路由问题。
由于创建了相同源站测试用例排查，因此出现了创建报错，目前已删除，可进行创建查看下。

**Comment by C018** [comment]
![IMG_20210715_160211](https://user-images.githubusercontent.com/43603829/125751938-4ebb15dd-2d4b-4ed4-8892-1f29a85b72ea.jpg)

**Comment by C018** [comment]
![IMG_20210715_160347](https://user-images.githubusercontent.com/43603829/125752117-a6cd9e45-bf9a-444a-9b6c-19575f095604.jpg)

**Comment by C018** [comment]
107.150.126.54 107.150.126.105延迟和路由都正常，其他30以上ms

**Comment by C018** [comment]
![IMG_20210715_160856](https://user-images.githubusercontent.com/43603829/125752981-527fbb90-a9a6-4bf6-bf0e-276db301a81d.jpg)

**Comment by C018** [comment]
![IMG_20210715_160938](https://user-images.githubusercontent.com/43603829/125753019-daf3a751-210d-4e5c-9087-b948aee336cf.jpg)

**Comment by C018** [comment]
目前出口节点ip
![IMG_20210715_161136](https://user-images.githubusercontent.com/43603829/125753268-f48d39ec-d7fc-4387-9af8-820621403b04.jpg)

**Comment by C018** [comment]
话说京韩还是沪韩延迟要低一点
