### ISSUE TITLE
有无可能增加国内IPv6接入

### ISSUE THREAD

**Issue by dndx** [hydra-yl/globals.sh#5]
首先感谢提供 GlobalSSH 这么好用的产品。

请问有无可能增加国内入口的IPv6接入？目前旗舰版已经支持源站使用 IPv6，如果接入也支持 IPv6 那么就可以全程不走 IPv4，对于纯 IPv6 环境也更加友好。

非常感谢！

**Comment by allensue325** [comment]
可以支持IPv6入口接入，依然增加在旗舰版的功能之上。预计可于8月初上线。

**Comment by dndx** [comment]
感谢回复！
