### ISSUE TITLE
北京到台北的线路延迟表现不太合理

### ISSUE THREAD

**Issue by aofei** [hydra-yl/globals.sh#8]
您好，打扰了。

经过实际测试发现，【`北京` -> `GSSH 台北`】线路的延迟意外地要高于【`北京` -> `GSSH 香港` -> `台北`】线路，我这里测试大概高了 `8ms` 左右。按理说 GSSH 出口直接选在`台北`这种全程走高速通道的方案肯定要比 GSSH 出口选在`香港`再绕行到`台北`要快才对，可实际测试结果却不是这样，请问这是什么原因导致的呢？

**Comment by allensue325** [comment]
能否告知下测试方法和两种线路测试的具体延迟。

**Comment by aofei** [comment]
我是用 [spook/sshping](https://github.com/spook/sshping) 这个工具进行测试的。

---

当 GSSH 出口选在`台北`时：

```
$ sshping -H as-server | grep 'Average-Latency'
Average-Latency:              68.8 ms
```

`我` -> `GSSH 北京入口` 平均延迟 `2.77 ms`

`GSSH 北京入口` -> `GSSH 台北出口` 平均延迟 `60.42 ms`

`GSSH 台北出口` -> `服务器` 平均延迟 `5.61 ms`

`2.77 ms` + `60.42 ms` + `5.61 ms` = `68.8 ms`

---

当 GSSH 出口选在`香港`时：

```
$ sshping -H as-server | grep 'Average-Latency'
Average-Latency:              57.9 ms
```

`我` -> `GSSH 北京入口` 平均延迟 `2.77 ms`

`GSSH 北京入口` -> `GSSH 香港出口` 平均延迟 `36.83 ms`

`GSSH 香港出口` -> `服务器` 平均延迟 `18.3 ms`

`2.77 ms` + `36.83 ms` + `18.3 ms` = `57.9 ms`

**Comment by allensue325** [comment]
我们自己创建了测试实例，源站在台北，使用sshping测试。

GSSH出口选在 台北 时，从北京主机至台北源站：
Average-Latency:              52 ms
GSSH出口选在 香港 时，从北京主机至台北源站：
Average-Latency:              56 ms

未能复现GSSH出口选在台北时的延迟情况，您邮箱对应账号下也未找到台北源站的GSSH实例所以无法进一步测试。
能否提供下台北源站信息并恢复GSSH台北出口的实例，已发送测试代金券在您账号下。

**Comment by aofei** [comment]
> 您邮箱对应账号下也未找到台北源站的GSSH实例所以无法进一步测试。

我是通过修改出口 IP 和地域来进行测试的，因为个人账号无法创建新的 GSSH 实例了。稍后晚一些我回去了更换成台北出口再测试一次。

**Comment by aofei** [comment]
我刚把 `GSSH 出口`更换成了`台北`，变更生效（也就是能 `ssh` 进去）后的 `sshping` 测试结果比较不稳定，但的确都在 `67 ms` 以上。

不过有意思的是，跟以往测试完不满意直接更换回`香港出口方案`不同，这次我在`台北出口方案`多等了大概 20 分钟左右，`台北出口方案`的 `sshping` 测试结果减少到跟`香港出口方案`持平了，都在 `57 ms` 左右。

结合着平台那边的测试结果总结来说，我的测试结果中的异常延迟并非线路本身原因导致的，更可能是更换 `GSSH 出口`后线路未能及时调整好造成的**临时现象**。

抱歉，我以为变更生效也就意味着线路已经调整好，事实上应该给它更多一点时间才对。

问题已解决，非常感谢您的帮助 @allensue325 ❤️～

**Comment by hydra-yl** [comment]
@allensue325 请看下上述变更成功，但延迟生效不及时的问题

**Comment by allensue325** [comment]
抱歉，等20分钟才恢复正常延迟是存在问题的，我们希望继续排查问题。
由于没有环境排查且未能复现，所以希望您能继续配合测试下。我们会在您账号下创建原本测试的台北实例，如果延迟依然67ms以上，请告知我们立刻进行后续的排查。
测试实例在控制台上可以查看和修改，希望您能继续反馈测试情况。

**Comment by aofei** [comment]
> 所以希望您能继续配合测试下

好的，明天我会再多来回切换着测试几次并反馈到这里。

**Comment by aofei** [comment]
我针对新实例的【服务器靠近区域】、【服务器 IP】、【服务器端口】这 3 个配置项进行了很多次不同组合的更换测试，都没能复现等 20 分钟左右才恢复正常延迟的情况，不过发现了一个新的问题。

更换到`香港`时，首次 SSH 成功出现在更换完成后的`第 5 秒`至`第 40 秒`之间，紧接着连续反复登录均成功。

更换到`台北`时，首次 SSH 成功出现在更换完成后的`第 30 秒`至`第 140 秒`之间，紧接着连续反复登录时`成功`与`失败`（指的是 SSH 超时）交替出现（即一次`成功`后必有一次`失败`），这种交替出现的现象消失在首次 SSH 成功后的`第 4 分钟`至`第 31 分钟`之间。

更换到`台北`时的`成功`与`失败`交替出现的现象在我这里可以 100% 复现。

我写了一行方便测试用的命令如下，如果有需要的话可以参考：

```
$ export gsshIP=<GSSH 北京入口 IP>; export gsshPort=<GSSH 端口>; export startTime=$(date +%H:%M:%S); while true; do echo -e "Start time:\t$startTime\nLap time:\t$(date +%H:%M:%S)"; ssh -o ConnectTimeout=1 -o StrictHostKeyChecking=no $gsshIP -p $gsshPort exit 2> /dev/null; echo -e "Exit code:\t$?\n"; done;
```

只用替换前面的 `<GSSH 北京入口 IP>` 和 `<GSSH 端口>` 即可使用，输出结果中的 `Exit code` 为 `0` 时表示登录成功，为 `255` 时表示 SSH 超时。

---

此外，截止到这条评论发出时，距离新实例的最新改动（我记得是先改了【服务器 IP】紧接着又改了【服务器端口】）已过去 10 分钟，到现在仍然未出现首次 SSH 成功。稍后出现首次成功后我会更新到这里。

更新 1：首次 SSH 成功出现在更换完成后的`第 18 分钟`前后，随后进入`成功`与`失败`交替出现的环节，消失后更新到这里。

更新 2：`成功`与`失败`交替出现的现象消失首次 SSH 成功后的`第 7 分钟`前后。
